# Generated by Django 4.1.7 on 2023-04-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="stats_sum",
        ),
        migrations.AddField(
            model_name="player",
            name="stats_sum",
            field=models.ManyToManyField(related_name="stats_sum", to="games.statsum"),
        ),
    ]
